### PR TITLE
Add disclaimer

### PR DESCRIPTION
**Pull request by dingobar**
Add disclaimer to the readme to explain that this repository is no longer maintained actively.

### CODE REVIEW

**Review by pacanada — APPROVED** [review]

**Review by pacanada — APPROVED** [review]

**Comment by pacanada** [comment]
It seems my review is not important :(

**Comment by dingobar** [comment]
> 

How so?

**Comment by pacanada** [comment]
No idea, I guess I am not included in reviewer list or something? I had the same problem for ds_toolbox repo

**Review by pacanada — APPROVED** [review]
and for the third time..!

**Pull request merged**
